#!/usr/bin/env ruby
# vim: set ft=ruby

require 'watir'
require 'headless'
require 'nokogiri'

class GoogleTranslateClient

	def initialize(options = {})
		@is_headless = options.fetch(:headless, false)
		@browser_engine = options.fetch(:browser_engine, :firefox)
	end

	def start
		if @is_headless
			begin
				@headless_engine = Headless.new
			rescue Headless::Exception => e
				if e.message == 'Xvfb not found on your system'
					puts e.message + ', try issuing the following command "sudo apt-get install xvfb"'
				end
				raise 'start failed'
			end
			@headless_engine.start
		end
		@browser = Watir::Browser.new :firefox
	end

	def translate(text)
		@browser.goto "https://translate.google.pl"
		@browser.execute_script "document.getElementById('source').value = '#{text}'"
		@browser.execute_script "document.querySelector('#gt-submit').click()"
		table_elem = @browser.element(:class => 'gt-baf-table')
		table_elem.wait_until_present
		html_table = @browser.execute_script "return document.querySelector('.gt-baf-table').outerHTML"
		puts self.parse_result_table(html_table)
	end

	def parse_result_table(html)
		doc = Nokogiri::HTML(html)
		return doc.css('div.gt-baf-word-clickable').text
	end

	def destroy
		if @is_headless
			@headless_engine.destroy
		end
		begin
			@browser.close
		rescue
		end
	end

end


gt = GoogleTranslateClient.new(:headless => true)

begin
	gt.start
rescue Exception => e
	puts "Exception => #{e}"
end
	gt.translate(ARGV[0])
	gt.destroy

